name: Build, Deploy, and Code Scanning

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on PRs to any branch
  schedule:
    - cron: '0 3 * * 1'  # Weekly scan at 3:00 AM every Monday

permissions:
  actions: read
  contents: read
  security-events: write  # Required for CodeQL to upload results

jobs:
  build-and-deploy:
    name: Build, Deploy, and Check Application Health
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for proper branch handling

      - name: Display GitHub Actor
        run: echo "The GitHub actor is $GITHUB_ACTOR"

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Spring Boot application
        run: mvn spring-boot:run &
        # Run Spring Boot in the background

      - name: Wait for 1 minute
        run: sleep 60  # Wait for the application to start

      - name: Check application health
        run: |
          echo "Checking application health..."
          curl -s --head http://localhost:8080/actuator/health | head -n 10

      - name: Stop Spring Boot application
        run: |
          echo "Stopping Spring Boot application..."
          mvn spring-boot:stop

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-artifacts
          path: target/

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build Codebase for CodeQL
        run: mvn clean install -DskipTests=true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
