name: Build, Deploy, and Check Application Health

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch, including feature branches.
  pull_request:
    branches:
      - master  # Triggers on PRs to the master branch from feature branches.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history for proper branch handling

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run Spring Boot application
      run: mvn spring-boot:run &
      # Run Spring Boot in the background

    - name: Wait for 5 minutes (simulate a long-running process)
      run: sleep 60  # Sleep for 5 minutes

    - name: Check application health
      run: |
        echo "Checking application health..."
        curl -s --head http://localhost:8080/actuator/health | head -n 10
      # Check if the health endpoint is up and responding

    - name: Stop Spring Boot application
      run: |
        echo "Stopping Spring Boot application..."
        pkill -f 'java -jar'  # This will stop the Spring Boot application process based on the command used to run it.
