name: Build and Run Pet Clinic

on:
  push:
    branches:
      - '**' # Trigger on push to any branch
  workflow_dispatch: # Allows manual trigger via GitHub Actions UI

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Cache Maven dependencies for faster builds
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Build the application
    - name: Build Application
      run: mvn clean install -DskipTests=true

    # Run the application
    - name: Run Application
      run: nohup java -jar target/petclinic.jar &

    # Verify the application
    - name: Verify Application
      run: |
        echo "Waiting for application to start..."
        sleep 10
        curl --fail http://localhost:8080 || (echo "Application is not running!" && exit 1)
