name: Build and Run Pet Clinic

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build Application
      run: mvn clean install -DskipTests=true
      working-directory: ./petclinic # Ensure you specify the correct subdirectory

    - name: Run Application
      run: nohup java -jar target/petclinic.jar &
      working-directory: ./petclinic # Specify the same subdirectory as above

    - name: Verify Application
      run: |
        echo "Waiting for application to start..."
        sleep 10
        curl --fail http://localhost:8080 || (echo "Application is not running!" && exit 1)
