name: Build and Deploy Petclinic

on:
  push:
    branches:
      - '**'   # Trigger on push to any branch (you can specify feature branches here)
  pull_request:
    branches:
      - '**'   # Trigger on PR to any branch (again, specify feature branches here)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full history is fetched (helps when working with feature branches)
        
    - name: List files to debug
      run: ls -R

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run Spring Boot application
      run: mvn spring-boot:run
