steps:
# Step 1: Checkout code
- name: Checkout code
  uses: actions/checkout@v3

# Step 2: Set up Java JDK (use the version compatible with your project)
- name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'  # Use the appropriate Java version for your project
    distribution: 'adoptopenjdk'

# Step 3: Cache Maven dependencies to speed up builds
- name: Cache Maven dependencies
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-

# Step 4: Install Maven dependencies and run tests
- name: Build with Maven
  run: mvn clean install

# Step 5: Run tests
- name: Run tests
  run: mvn test

# Step 6: Run the Spring Boot Application (optional)
- name: Run Spring Boot Application
  run: mvn spring-boot:run
  env:
    SPRING_PROFILES_ACTIVE: github-actions
