name: Java CI with Maven

on:
  push:
    branches:
      - master
      - 'feature/*'  # Update this for feature branches if required

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project (skip tests for faster builds)
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 4: Run your application (example command for Spring Boot)
      - name: Run Spring Boot application
        run: java -jar target/petclinic-0.0.1-SNAPSHOT.jar &

      # Step 5: Sleep for 1 minute (or adjust as needed)
      - name: Sleep for 1 minute
        run: sleep 60

      # Step 6: Check application health (optional)
      - name: Check application health
        run: |
          echo "Checking application health..."
          curl -s --head http://localhost:8080/actuator/health | head -n 10

      # Step 7: Stop the Spring Boot application (this step is optional)
      - name: Stop Spring Boot application
        run: pkill -f 'java -jar'

      # Step 8: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: petclinic-artifacts
          path: |
            target/*.jar  # Adjust the path to your actual artifact location
            logs/          # Optionally add any log files you want to upload
